name: zoo
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.10
    - pandas
    - pytables
    - pyside6
    - vtk>=9.1.0
    - pyvista=0.38
    - pyvistaqt
    - scipy
    - pyperclip
    - pywin32
    - colorcet
    - matplotlib
