name: zoo
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.10
    - numpy=1.24
    - pandas=1.5
    - pytables
    - pyqt
    - vtk=9.2
    - pyvista=0.37
    - pyvistaqt
    - scipy=1.10
    - pyperclip
    - pywin32
    - colorcet
    - matplotlib=3.6
