name: zoo
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - pandas
    - pytables
    - pyqt
    - vtk>=9.1.0
    - pyvista
    - pyvistaqt
    - scipy
    - pyperclip
    - pywin32
