# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zoo.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(835, 641)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.viewport = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewport.sizePolicy().hasHeightForWidth())
        self.viewport.setSizePolicy(sizePolicy)
        self.viewport.setMinimumSize(QtCore.QSize(300, 0))
        self.viewport.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.viewport.setFrameShadow(QtWidgets.QFrame.Raised)
        self.viewport.setObjectName("viewport")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.viewport)
        self.horizontalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout.addWidget(self.viewport)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(3)
        self.line.setMidLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.controlPane = QtWidgets.QFrame(self.centralwidget)
        self.controlPane.setEnabled(True)
        self.controlPane.setMaximumSize(QtCore.QSize(200, 16777215))
        self.controlPane.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controlPane.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controlPane.setObjectName("controlPane")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.controlPane)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.controls = QtWidgets.QVBoxLayout()
        self.controls.setObjectName("controls")
        self.timeStepSelection = QtWidgets.QHBoxLayout()
        self.timeStepSelection.setSpacing(0)
        self.timeStepSelection.setObjectName("timeStepSelection")
        self.prevTimeStep = QtWidgets.QPushButton(self.controlPane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevTimeStep.sizePolicy().hasHeightForWidth())
        self.prevTimeStep.setSizePolicy(sizePolicy)
        self.prevTimeStep.setMaximumSize(QtCore.QSize(20, 16777215))
        self.prevTimeStep.setBaseSize(QtCore.QSize(16, 16))
        self.prevTimeStep.setObjectName("prevTimeStep")
        self.timeStepSelection.addWidget(self.prevTimeStep)
        self.timeStepSelector = QtWidgets.QComboBox(self.controlPane)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.timeStepSelector.setFont(font)
        self.timeStepSelector.setEditable(False)
        self.timeStepSelector.setCurrentText("")
        self.timeStepSelector.setObjectName("timeStepSelector")
        self.timeStepSelection.addWidget(self.timeStepSelector)
        self.nextTimeStep = QtWidgets.QPushButton(self.controlPane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextTimeStep.sizePolicy().hasHeightForWidth())
        self.nextTimeStep.setSizePolicy(sizePolicy)
        self.nextTimeStep.setMaximumSize(QtCore.QSize(20, 16777215))
        self.nextTimeStep.setBaseSize(QtCore.QSize(16, 16))
        self.nextTimeStep.setCheckable(False)
        self.nextTimeStep.setAutoRepeat(False)
        self.nextTimeStep.setFlat(False)
        self.nextTimeStep.setObjectName("nextTimeStep")
        self.timeStepSelection.addWidget(self.nextTimeStep)
        self.controls.addLayout(self.timeStepSelection)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.controls.addItem(spacerItem)
        self.glyphOptionGrid = QtWidgets.QGridLayout()
        self.glyphOptionGrid.setHorizontalSpacing(6)
        self.glyphOptionGrid.setVerticalSpacing(8)
        self.glyphOptionGrid.setObjectName("glyphOptionGrid")
        self.gsLabel = QtWidgets.QLabel(self.controlPane)
        self.gsLabel.setObjectName("gsLabel")
        self.glyphOptionGrid.addWidget(self.gsLabel, 0, 0, 1, 1)
        self.gsSpinBox = QtWidgets.QDoubleSpinBox(self.controlPane)
        self.gsSpinBox.setMinimumSize(QtCore.QSize(80, 0))
        self.gsSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.gsSpinBox.setDecimals(5)
        self.gsSpinBox.setMinimum(1e-05)
        self.gsSpinBox.setMaximum(9999999.0)
        self.gsSpinBox.setSingleStep(0.005)
        self.gsSpinBox.setProperty("value", 0.01)
        self.gsSpinBox.setObjectName("gsSpinBox")
        self.glyphOptionGrid.addWidget(self.gsSpinBox, 0, 1, 1, 1)
        self.exagLabel = QtWidgets.QLabel(self.controlPane)
        self.exagLabel.setWordWrap(True)
        self.exagLabel.setObjectName("exagLabel")
        self.glyphOptionGrid.addWidget(self.exagLabel, 1, 0, 1, 1)
        self.exagSpinBox = QtWidgets.QDoubleSpinBox(self.controlPane)
        self.exagSpinBox.setMinimumSize(QtCore.QSize(80, 0))
        self.exagSpinBox.setDecimals(1)
        self.exagSpinBox.setObjectName("exagSpinBox")
        self.glyphOptionGrid.addWidget(self.exagSpinBox, 1, 1, 1, 1)
        self.controls.addLayout(self.glyphOptionGrid)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.controls.addItem(spacerItem1)
        self.contourDataGroup = QtWidgets.QGroupBox(self.controlPane)
        self.contourDataGroup.setEnabled(True)
        self.contourDataGroup.setObjectName("contourDataGroup")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.contourDataGroup)
        self.verticalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.datasetSelector = QtWidgets.QComboBox(self.contourDataGroup)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.datasetSelector.setFont(font)
        self.datasetSelector.setObjectName("datasetSelector")
        self.verticalLayout_4.addWidget(self.datasetSelector)
        self.colorlimitLabel = QtWidgets.QLabel(self.contourDataGroup)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.colorlimitLabel.setFont(font)
        self.colorlimitLabel.setObjectName("colorlimitLabel")
        self.verticalLayout_4.addWidget(self.colorlimitLabel)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.colorCheckBox = QtWidgets.QCheckBox(self.contourDataGroup)
        self.colorCheckBox.setText("")
        self.colorCheckBox.setObjectName("colorCheckBox")
        self.horizontalLayout_6.addWidget(self.colorCheckBox)
        self.colorminSpinBox = QtWidgets.QDoubleSpinBox(self.contourDataGroup)
        self.colorminSpinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.colorminSpinBox.setFont(font)
        self.colorminSpinBox.setDecimals(3)
        self.colorminSpinBox.setMinimum(-99999999999.0)
        self.colorminSpinBox.setMaximum(99999999999.0)
        self.colorminSpinBox.setObjectName("colorminSpinBox")
        self.horizontalLayout_6.addWidget(self.colorminSpinBox)
        self.colormaxSpinBox = QtWidgets.QDoubleSpinBox(self.contourDataGroup)
        self.colormaxSpinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.colormaxSpinBox.setFont(font)
        self.colormaxSpinBox.setDecimals(3)
        self.colormaxSpinBox.setMinimum(-99999999999.0)
        self.colormaxSpinBox.setMaximum(99999999999.0)
        self.colormaxSpinBox.setObjectName("colormaxSpinBox")
        self.horizontalLayout_6.addWidget(self.colormaxSpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.maskingLabel = QtWidgets.QLabel(self.contourDataGroup)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.maskingLabel.setFont(font)
        self.maskingLabel.setObjectName("maskingLabel")
        self.verticalLayout_4.addWidget(self.maskingLabel)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.maskCheckBox = QtWidgets.QCheckBox(self.contourDataGroup)
        self.maskCheckBox.setText("")
        self.maskCheckBox.setObjectName("maskCheckBox")
        self.horizontalLayout_7.addWidget(self.maskCheckBox)
        self.maskminSpinBox = QtWidgets.QDoubleSpinBox(self.contourDataGroup)
        self.maskminSpinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.maskminSpinBox.setFont(font)
        self.maskminSpinBox.setDecimals(3)
        self.maskminSpinBox.setMinimum(-99999999999.0)
        self.maskminSpinBox.setMaximum(99999999999.0)
        self.maskminSpinBox.setObjectName("maskminSpinBox")
        self.horizontalLayout_7.addWidget(self.maskminSpinBox)
        self.maskmaxSpinBox = QtWidgets.QDoubleSpinBox(self.contourDataGroup)
        self.maskmaxSpinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.maskmaxSpinBox.setFont(font)
        self.maskmaxSpinBox.setDecimals(3)
        self.maskmaxSpinBox.setMinimum(-99999999999.0)
        self.maskmaxSpinBox.setMaximum(99999999999.0)
        self.maskmaxSpinBox.setObjectName("maskmaxSpinBox")
        self.horizontalLayout_7.addWidget(self.maskmaxSpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.controls.addWidget(self.contourDataGroup)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.controls.addItem(spacerItem2)
        self.extentsGroup = QtWidgets.QGroupBox(self.controlPane)
        self.extentsGroup.setObjectName("extentsGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.extentsGroup)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.zminSpinBox = QtWidgets.QDoubleSpinBox(self.extentsGroup)
        self.zminSpinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.zminSpinBox.setFont(font)
        self.zminSpinBox.setDecimals(3)
        self.zminSpinBox.setMinimum(-99999999999.0)
        self.zminSpinBox.setMaximum(99999999999.0)
        self.zminSpinBox.setObjectName("zminSpinBox")
        self.gridLayout_2.addWidget(self.zminSpinBox, 3, 2, 1, 1)
        self.zLabel = QtWidgets.QLabel(self.extentsGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zLabel.sizePolicy().hasHeightForWidth())
        self.zLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.zLabel.setFont(font)
        self.zLabel.setScaledContents(False)
        self.zLabel.setObjectName("zLabel")
        self.gridLayout_2.addWidget(self.zLabel, 3, 0, 1, 1)
        self.ymaxSpinBox = QtWidgets.QDoubleSpinBox(self.extentsGroup)
        self.ymaxSpinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ymaxSpinBox.setFont(font)
        self.ymaxSpinBox.setDecimals(3)
        self.ymaxSpinBox.setMinimum(-99999999999.0)
        self.ymaxSpinBox.setMaximum(99999999999.0)
        self.ymaxSpinBox.setObjectName("ymaxSpinBox")
        self.gridLayout_2.addWidget(self.ymaxSpinBox, 2, 3, 1, 1)
        self.xLabel = QtWidgets.QLabel(self.extentsGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xLabel.sizePolicy().hasHeightForWidth())
        self.xLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.xLabel.setFont(font)
        self.xLabel.setScaledContents(False)
        self.xLabel.setObjectName("xLabel")
        self.gridLayout_2.addWidget(self.xLabel, 0, 0, 1, 1)
        self.zmaxSpinBox = QtWidgets.QDoubleSpinBox(self.extentsGroup)
        self.zmaxSpinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.zmaxSpinBox.setFont(font)
        self.zmaxSpinBox.setDecimals(3)
        self.zmaxSpinBox.setMinimum(-99999999999.0)
        self.zmaxSpinBox.setMaximum(99999999999.0)
        self.zmaxSpinBox.setObjectName("zmaxSpinBox")
        self.gridLayout_2.addWidget(self.zmaxSpinBox, 3, 3, 1, 1)
        self.yLabel = QtWidgets.QLabel(self.extentsGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yLabel.sizePolicy().hasHeightForWidth())
        self.yLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.yLabel.setFont(font)
        self.yLabel.setScaledContents(False)
        self.yLabel.setObjectName("yLabel")
        self.gridLayout_2.addWidget(self.yLabel, 2, 0, 1, 1)
        self.xmaxSpinBox = QtWidgets.QDoubleSpinBox(self.extentsGroup)
        self.xmaxSpinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.xmaxSpinBox.setFont(font)
        self.xmaxSpinBox.setDecimals(3)
        self.xmaxSpinBox.setMinimum(-99999999999.0)
        self.xmaxSpinBox.setMaximum(99999999999.0)
        self.xmaxSpinBox.setObjectName("xmaxSpinBox")
        self.gridLayout_2.addWidget(self.xmaxSpinBox, 0, 3, 1, 1)
        self.xminSpinBox = QtWidgets.QDoubleSpinBox(self.extentsGroup)
        self.xminSpinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.xminSpinBox.setFont(font)
        self.xminSpinBox.setDecimals(3)
        self.xminSpinBox.setMinimum(-99999999999.0)
        self.xminSpinBox.setMaximum(99999999999.0)
        self.xminSpinBox.setObjectName("xminSpinBox")
        self.gridLayout_2.addWidget(self.xminSpinBox, 0, 2, 1, 1)
        self.yminSpinBox = QtWidgets.QDoubleSpinBox(self.extentsGroup)
        self.yminSpinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.yminSpinBox.setFont(font)
        self.yminSpinBox.setDecimals(3)
        self.yminSpinBox.setMinimum(-99999999999.0)
        self.yminSpinBox.setMaximum(99999999999.0)
        self.yminSpinBox.setObjectName("yminSpinBox")
        self.gridLayout_2.addWidget(self.yminSpinBox, 2, 2, 1, 1)
        self.xclipCheckBox = QtWidgets.QCheckBox(self.extentsGroup)
        self.xclipCheckBox.setText("")
        self.xclipCheckBox.setObjectName("xclipCheckBox")
        self.gridLayout_2.addWidget(self.xclipCheckBox, 0, 1, 1, 1)
        self.yclipCheckBox = QtWidgets.QCheckBox(self.extentsGroup)
        self.yclipCheckBox.setText("")
        self.yclipCheckBox.setObjectName("yclipCheckBox")
        self.gridLayout_2.addWidget(self.yclipCheckBox, 2, 1, 1, 1)
        self.zclipCheckBox = QtWidgets.QCheckBox(self.extentsGroup)
        self.zclipCheckBox.setText("")
        self.zclipCheckBox.setObjectName("zclipCheckBox")
        self.gridLayout_2.addWidget(self.zclipCheckBox, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.controls.addWidget(self.extentsGroup)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.controls.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.controls)
        self.horizontalLayout.addWidget(self.controlPane)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 835, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionShow_Grid = QtWidgets.QAction(MainWindow)
        self.actionShow_Grid.setObjectName("actionShow_Grid")
        self.actionClear_Grid_Cache = QtWidgets.QAction(MainWindow)
        self.actionClear_Grid_Cache.setObjectName("actionClear_Grid_Cache")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionShow_Grid)
        self.menuView.addAction(self.actionClear_Grid_Cache)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.gsLabel.setBuddy(self.gsSpinBox)
        self.exagLabel.setBuddy(self.exagSpinBox)
        self.colorlimitLabel.setBuddy(self.colorminSpinBox)
        self.maskingLabel.setBuddy(self.maskminSpinBox)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.prevTimeStep, self.timeStepSelector)
        MainWindow.setTabOrder(self.timeStepSelector, self.nextTimeStep)
        MainWindow.setTabOrder(self.nextTimeStep, self.gsSpinBox)
        MainWindow.setTabOrder(self.gsSpinBox, self.exagSpinBox)
        MainWindow.setTabOrder(self.exagSpinBox, self.datasetSelector)
        MainWindow.setTabOrder(self.datasetSelector, self.colorminSpinBox)
        MainWindow.setTabOrder(self.colorminSpinBox, self.colormaxSpinBox)
        MainWindow.setTabOrder(self.colormaxSpinBox, self.maskminSpinBox)
        MainWindow.setTabOrder(self.maskminSpinBox, self.maskmaxSpinBox)
        MainWindow.setTabOrder(self.maskmaxSpinBox, self.xminSpinBox)
        MainWindow.setTabOrder(self.xminSpinBox, self.xmaxSpinBox)
        MainWindow.setTabOrder(self.xmaxSpinBox, self.yminSpinBox)
        MainWindow.setTabOrder(self.yminSpinBox, self.ymaxSpinBox)
        MainWindow.setTabOrder(self.ymaxSpinBox, self.zminSpinBox)
        MainWindow.setTabOrder(self.zminSpinBox, self.zmaxSpinBox)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.prevTimeStep.setText(_translate("MainWindow", "<-"))
        self.prevTimeStep.setShortcut(_translate("MainWindow", "Ctrl+Left"))
        self.nextTimeStep.setText(_translate("MainWindow", "->"))
        self.nextTimeStep.setShortcut(_translate("MainWindow", "Ctrl+Right"))
        self.gsLabel.setText(_translate("MainWindow", "Grid Spacing"))
        self.exagLabel.setText(_translate("MainWindow", "Exaggeration"))
        self.contourDataGroup.setTitle(_translate("MainWindow", "Contour Data"))
        self.colorlimitLabel.setText(_translate("MainWindow", "Color Limits"))
        self.maskingLabel.setText(_translate("MainWindow", "Masking Thresholds"))
        self.extentsGroup.setTitle(_translate("MainWindow", "Clipping Extents"))
        self.zLabel.setText(_translate("MainWindow", "Z"))
        self.xLabel.setText(_translate("MainWindow", "X"))
        self.yLabel.setText(_translate("MainWindow", "Y"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionShow_Grid.setText(_translate("MainWindow", "Show Grid"))
        self.actionClear_Grid_Cache.setText(_translate("MainWindow", "Clear Grid Cache"))
