{% set name = "zoo" %}
{% set version = "0.10.0" %}

package:
    name: "{{ name|lower }}"
    version: "{{ version }}"

source:
    git_rev: "{{ version }}"
    git_url: https://github.com/CMSM-VCU/zoo.git

build:
    script: python setup.py install --single-version-externally-managed --record=record.txt
    noarch: python
    entry_points:
        - zoo = zoo:run

requirements:
    build:
        - python >=3.10.0
        - setuptools
        - pytables
        - pandas
        - pyqt
        - vtk >=9.1.0
        - pyvista <0.37.0
        - pyvistaqt
        - scipy
        - pyperclip
        - pywin32
        - matplotlib
        - colorcet

    run:
        - python >=3.10.0
        - pytables
        - pandas
        - pyqt
        - vtk >=9.1.0
        - pyvista <0.37.0
        - pyvistaqt
        - scipy
        - pyperclip
        - pywin32
        - matplotlib
        - colorcet

test:
    imports:
        - zoo

about:
    home: "https://github.com/CMSM-VCU/zoo"
    license: MIT
    license_family: MIT
    summary: "A tool for visualizing Peridynamic simulation results"
