{% set name = "zoo" %}
{% set version = "0.10.4" %}

package:
    name: "{{ name|lower }}"
    version: "{{ version }}"

source:
    git_rev: "{{ version }}"
    git_url: https://github.com/CMSM-VCU/zoo.git

build:
    script: python setup.py install --single-version-externally-managed --record=record.txt
    noarch: python
    entry_points:
        - zoo = zoo:run

requirements:
    build:
        - python ==3.10
        - setuptools
        - numpy
        - pytables
        - pandas <=1.5
        - pyqt
        - vtk ==9.1
        - pyvista ==0.37
        - pyvistaqt
        - scipy <=1.10
        - pyperclip
        - pywin32
        - matplotlib
        - colorcet

    run:
        - python ==3.10
        - numpy
        - pytables
        - pandas <=1.5
        - pyqt
        - vtk ==9.1
        - pyvista ==0.37
        - pyvistaqt
        - scipy <=1.10
        - pyperclip
        - pywin32
        - matplotlib
        - colorcet

test:
    imports:
        - zoo

about:
    home: "https://github.com/CMSM-VCU/zoo"
    license: MIT
    license_family: MIT
    summary: "A tool for visualizing Peridynamic simulation results"
