{% set name = "zoo" %}
{% set version = "0.10.3" %}

package:
    name: "{{ name|lower }}"
    version: "{{ version }}"

source:
    git_rev: "{{ version }}"
    git_url: https://github.com/CMSM-VCU/zoo.git

build:
    script: python setup.py install --single-version-externally-managed --record=record.txt
    noarch: python
    entry_points:
        - zoo = zoo:run

requirements:
    build:
        - python ==3.10.*
        - setuptools
        - numpy <=1.24.*
        - pytables <=3.7.*
        - pandas <=1.5.*
        - pyqt <=5.15.*
        - vtk ==9.1.*
        - pyvista ==0.37.*
        - pyvistaqt <=0.9.*
        - scipy <=1.10.*
        - pyperclip
        - pywin32
        - matplotlib <=3.6.*
        - colorcet

    run:
        - python ==3.10.*
        - numpy <=1.24.*
        - pytables <=3.7.*
        - pandas <=1.5.*
        - pyqt <=5.15.*
        - vtk ==9.1.*
        - pyvista ==0.37.*
        - pyvistaqt <=0.9.*
        - scipy <=1.10.*
        - pyperclip
        - pywin32
        - matplotlib <=3.6.*
        - colorcet

test:
    imports:
        - zoo

about:
    home: "https://github.com/CMSM-VCU/zoo"
    license: MIT
    license_family: MIT
    summary: "A tool for visualizing Peridynamic simulation results"
