{% set name = "zoo" %}

package:
    name: "{{ name|lower }}"
    version: "{{ environ['GIT_DESCRIBE_TAG'] }}"

source:
    git_rev: "{{ environ['GIT_DESCRIBE_TAG'] }}"
    git_url: https://github.com/CMSM-VCU/zoo.git

build:
    script: python setup.py install --single-version-externally-managed --record=record.txt
    noarch: python
    entry_points:
        - zoo = zoo:run
    string: {{ GIT_BUILD_STR }}

requirements:
    build:
        - python >=3.10
        - setuptools
        - pytables
        - pandas
        - pyside6
        - qt6-main <=6.6.0 # Fatal error introduced in 6.6.1
        - vtk >=9.1.0
        - pyvista >=0.38
        - pyvistaqt
        - scipy
        - pyperclip
        - pywin32
        - matplotlib-base
        - colorcet

    run:
        - python >=3.10
        - pytables
        - pandas
        - pyside6
        - qt6-main <=6.6.0 # Fatal error introduced in 6.6.1
        - vtk >=9.1.0
        - pyvista >=0.38
        - pyvistaqt
        - scipy
        - pyperclip
        - pywin32
        - matplotlib-base
        - colorcet

test:
    imports:
        - zoo

about:
    home: "https://github.com/CMSM-VCU/zoo"
    license: MIT
    license_family: MIT
    summary: "A tool for visualizing Peridynamic simulation results"
